#+TITLE: Funnel

Funnel is an experiment in leveraging plain ol' filesystem for processing
network requests, such as email and webhooks, via Dropbox. The *philosophy
behind funnel* is to facilitate the use of simple UNIX tools for processing data
that spans the network. As an *example*, the command =cat ${FILE} >>
org/Inbox.org= is all that is needed to process an incoming email (stored in
Dropbox) from the user requesting an addition of GTD inbox item to their org
file stored in Dropbox.

** Brainstorming

- Email to append-to-Dropbox
- Unix tools pipeped, processing on new content in Dropbox
- Possibly, tools write back to trigger remote actions (http request, email response, etc.)

** TODO MVP 
SCHEDULED: <2015-08-15 Sat>
- [X] Create a Heroku app with a suitable /mail addon/.
  - [X] Write app.json
  - [X] Write Hello world server 
  - [X] Verify the mail addon
    - [X] Resolve sender signature troubles (!)
    - [X] Verify webhook works
      - [X] Fix Flask.g not working
        - [X] Switch to Pyramid!
      - [X] Log webhook data
- [X] Use Dropbox app folder API
  - [X] Pick an API and language
  - [X] Get oauth flow working
    - [X] Configure pyramid session
- [ ] Test by writing to hello.txt
  - [ ] Persist oauth token in env var
  - [ ] Write file!
