#+TITLE: Funnel

Funnel is an experiment in leveraging plain ol' filesystem for processing
network requests, such as email and webhooks, via Dropbox. The *philosophy
behind funnel* is to facilitate the use of simple UNIX tools for processing data
that spans the network. As an *example*, the command =cat ${FILE} >>
org/Inbox.org= is all that is needed to process an incoming email (stored in
Dropbox) from the user requesting an addition of GTD inbox item to their org
file stored in Dropbox.

** Current design

- Email to Dropbox
- Unix tools pipeped, processing on new content in Dropbox
- Possibly, tools write back to trigger remote actions (http request, email response, etc.)

** DONE MVP 
CLOSED: [2015-08-15 Sat 17:57] SCHEDULED: <2015-08-15 Sat>
- [X] Create a Heroku app with a suitable /mail addon/.
  - [X] Write app.json
  - [X] Write Hello world server 
  - [X] Verify the mail addon
    - [X] Resolve sender signature troubles (!)
    - [X] Verify webhook works
      - [X] Fix Flask.g not working
        - [X] Switch to Pyramid!
      - [X] Log webhook data
- [X] Use Dropbox app folder API
  - [X] Pick an API and language
  - [X] Get oauth flow working
    - [X] Configure pyramid session
- [X] Test by writing to hello.txt
  - [X] Persist oauth token in env var
  - [X] Write file!
- [X] Append to the file instead
** TODO Stage II work

Implementation
- [X] Write inbound message as JSON to timestamped files
- [X] Write CLI to append to Inbox.org
- [ ] Configure basic auth
  - [ ] Ensure it works with postmark
  - [ ] Ensure it works with dropbox oauth

** TODO Go public [0/8]
- [ ] Rename project, if necessary.
- [ ] Add Heroku button
- [ ] Enable Dropbox oauth for everyone
- [ ] UI & UX
- [ ] Make repo public
- [ ] Test!
- [ ] Blog post
- [ ] Announce (HN, reddit, mailing lists


** HOWTO
- Deploy using app.json (automatically creates postmark and papertrail accounts)
  - Go to Dropbox, and create an app. Set app key and secret here.
- Take a note of $PASSWORD from heroku config
  - =export APPURL=https://user:${PASSWORD}@${APPNAME}.herokuapp.com=
- Set Dropbox's oauth redirect url to =${APPURL}/dropboxauth=
- Visit https://<thisapp>.herokuapp.com/ to complete oauth flow
  - Run the specified TOKEN cli
- =heroku addon:open postmark= and point the inbound URL to =${APPURL}/incoming=
- Send a test email to your postmark inbound address

*** Processing JSON files

Funnel creates timestamped JSON file for each incoming email. Here is a poller
that appends to Inbox.org for each incoming message:

#+BEGIN_SRC bash
  while true; do find . -name "*.json" -print0 | xargs -r -n 1 ~/Dropbox/org/toinbox.sh; sleep 2; done
#+END_SRC

The =toinbox.sh= script may look like:

#+BEGIN_SRC bash
  #!/bin/bash
  set -e

  json=$1

  title() {
      jq -r .Subject $json
  }

  body() {
      # The `sed` removes \r
      jq -r .TextBody $json | sed ':a;N;$!ba;s/\r//g'
  }

  inboxfile=~/Dropbox/org/Inbox.org

  echo "** TODO `title`" >> $inboxfile
  body >> $inboxfile
  # echo >> $inboxfile  # ensure newline

  rm $json

#+END_SRC
